CREATE EXTENSION IF NOT EXISTS citext;

-- AlterTable
ALTER TABLE "medium_of_instructions" ALTER COLUMN "name" SET DATA TYPE CITEXT,
ALTER COLUMN "code" SET DATA TYPE CITEXT;

-- AlterTable
ALTER TABLE "subjects" ALTER COLUMN "name" SET DATA TYPE CITEXT,
ALTER COLUMN "abbreviation" SET DATA TYPE CITEXT;
